import type { Trademark, User } from "./types";

export const DEMO_USERS: User[] = [
  {
    id: "u-demo",
    name: "演示用户",
    avatar: "演",
    phone: "138****8888",
    wechatId: "maibo_demo",
  },
];

const defaultItems = [
  { name: "计算机程序（可下载软件）", group: "0901" },
  { name: "可下载的电子出版物", group: "0901" },
  { name: "电子数据处理设备", group: "0901" },
  { name: "计算机网络设备", group: "0907" },
  { name: "网络通讯设备", group: "0907" },
  { name: "卫星导航仪器", group: "0907" },
  { name: "音频视频接收器", group: "0908" },
  { name: "扬声器音箱", group: "0908" },
  { name: "智能手表（数据处理）", group: "0901" },
  { name: "可穿戴智能设备", group: "0901" },
];

export const SEED_TRADEMARKS: Trademark[] = [
  {
    id: "tm-1",
    name: "驼典",
    initial: "驼",
    registrationNo: "71234567",
    categoryCode: 9,
    categoryName: "电子电器",
    price: 7400,
    itemCount: 10,
    sameNameClasses: 1,
    gradient: "from-[#2E6BFF] to-[#5989FF]",
    status: "available",
    hot: true,
    scenes: ["ecommerce", "tech"],
    aiScore: 92,
    aiTags: ["易记性高", "行业匹配度好", "传播力强"],
    aiReason: "名称简短有力，适合电商平台品牌定位",
    aiEvaluation:
      '"驼典"二字组合具有强烈的品牌辨识度，"驼"字蕴含稳健、持久的行业形象，与09类电子电器产品中追求可靠性、耐久性的用户诉求高度契合。',
    riskScore: 92,
    riskLevel: "low",
    riskItems: [
      { text: "无近似驳回风险", ok: true },
      { text: "权属清晰无纠纷", ok: true },
      { text: "有效期充足 (>8年)", ok: true },
      { text: "同名存在1类", ok: false, note: "(仅供参考)" },
    ],
    items: defaultItems,
    applyDate: "2023-06-15",
    registerDate: "2024-03-14",
    expireDate: "2034-03-13",
    applicant: "武汉某某科技有限公司",
    similarGroups: "0901, 0907, 0908",
  },
  {
    id: "tm-2",
    name: "惊兽",
    initial: "兽",
    registrationNo: "71234568",
    categoryCode: 25,
    categoryName: "服装鞋帽",
    price: 6499,
    originalPrice: 12800,
    itemCount: 8,
    sameNameClasses: 4,
    gradient: "from-[#00C9A7] to-[#6AD9BA]",
    status: "available",
    hot: true,
    scenes: ["fashion"],
    aiScore: 85,
    aiTags: ["辨识度高", "年轻化"],
    aiReason: "名称独特，适合潮流服饰品牌",
    riskScore: 88,
    riskLevel: "low",
    riskItems: [
      { text: "无近似驳回风险", ok: true },
      { text: "权属清晰无纠纷", ok: true },
      { text: "有效期充足", ok: true },
    ],
    items: [
      { name: "服装", group: "2501" },
      { name: "鞋", group: "2507" },
      { name: "帽", group: "2508" },
    ],
    applyDate: "2022-08-10",
    registerDate: "2023-05-20",
    expireDate: "2033-05-19",
    applicant: "上海某某服饰有限公司",
    similarGroups: "2501, 2507",
  },
  {
    id: "tm-3",
    name: "HIPUNA",
    initial: "HP",
    registrationNo: "71234569",
    categoryCode: 9,
    categoryName: "电子电器",
    price: 7400,
    itemCount: 12,
    sameNameClasses: 2,
    gradient: "from-[#FF6B35] to-[#FF9B6A]",
    status: "available",
    hot: true,
    scenes: ["ecommerce", "tech"],
    aiScore: 88,
    aiTags: ["国际感强", "跨境友好"],
    aiReason: "英文名适合跨境电商业态，国际感强",
    riskScore: 90,
    riskLevel: "low",
    riskItems: [
      { text: "无近似驳回风险", ok: true },
      { text: "权属清晰无纠纷", ok: true },
      { text: "有效期充足", ok: true },
    ],
    items: defaultItems.slice(0, 8),
    applyDate: "2023-01-20",
    registerDate: "2023-11-08",
    expireDate: "2033-11-07",
    applicant: "深圳某某贸易有限公司",
    similarGroups: "0901, 0907",
  },
  {
    id: "tm-4",
    name: "卓状元 ZUOSLEAD",
    initial: "卓",
    registrationNo: "71234570",
    categoryCode: 43,
    categoryName: "餐饮住宿",
    price: 6499,
    itemCount: 6,
    sameNameClasses: 1,
    gradient: "from-[#F59E0B] to-[#FCD34D]",
    status: "available",
    hot: true,
    scenes: ["food", "education"],
    aiScore: 86,
    aiTags: ["寓意好", "教育场景"],
    aiReason: "含「状元」寓意，适合教育/培训场景",
    riskScore: 87,
    riskLevel: "low",
    riskItems: [
      { text: "无近似驳回风险", ok: true },
      { text: "权属清晰无纠纷", ok: true },
      { text: "有效期充足", ok: true },
    ],
    items: [
      { name: "餐厅", group: "4301" },
      { name: "咖啡馆", group: "4302" },
    ],
    applyDate: "2022-03-12",
    registerDate: "2022-12-01",
    expireDate: "2032-11-30",
    applicant: "北京某某餐饮管理有限公司",
    similarGroups: "4301, 4302",
  },
  {
    id: "tm-5",
    name: "SUOSKILL 索巧",
    initial: "索",
    registrationNo: "71234571",
    categoryCode: 9,
    categoryName: "电子电器",
    price: 5800,
    itemCount: 15,
    sameNameClasses: 3,
    gradient: "from-[#FF6B35] to-[#FFB088]",
    status: "available",
    scenes: ["tech"],
    aiScore: 82,
    aiTags: ["中英组合", "科技感"],
    aiReason: "中英组合名称，适合科技产品",
    riskScore: 85,
    riskLevel: "low",
    riskItems: [
      { text: "无近似驳回风险", ok: true },
      { text: "权属清晰无纠纷", ok: true },
      { text: "有效期充足", ok: true },
    ],
    items: defaultItems,
    applyDate: "2021-09-05",
    registerDate: "2022-06-18",
    expireDate: "2032-06-17",
    applicant: "杭州某某科技有限公司",
    similarGroups: "0901, 0908",
  },
  {
    id: "tm-6",
    name: "龙击科技",
    initial: "龙",
    registrationNo: "71234572",
    categoryCode: 9,
    categoryName: "电子电器",
    price: 7400,
    itemCount: 11,
    sameNameClasses: 4,
    gradient: "from-[#EC4899] to-[#F9A8D4]",
    status: "available",
    scenes: ["tech"],
    aiScore: 84,
    aiTags: ["力量感", "科技行业"],
    aiReason: "名称有力，适合科技类企业",
    riskScore: 86,
    riskLevel: "low",
    riskItems: [
      { text: "无近似驳回风险", ok: true },
      { text: "权属清晰无纠纷", ok: true },
      { text: "有效期充足", ok: true },
    ],
    items: defaultItems.slice(0, 6),
    applyDate: "2020-11-22",
    registerDate: "2021-08-30",
    expireDate: "2031-08-29",
    applicant: "成都某某信息技术有限公司",
    similarGroups: "0901, 0907",
  },
  {
    id: "tm-7",
    name: "企早早",
    initial: "企",
    registrationNo: "71234573",
    categoryCode: 35,
    categoryName: "广告销售",
    price: 6499,
    itemCount: 9,
    sameNameClasses: 1,
    gradient: "from-[#06B6D4] to-[#67E8F9]",
    status: "available",
    scenes: ["ecommerce"],
    aiScore: 80,
    aiTags: ["企业服务", "易传播"],
    aiReason: "适合企业服务与广告销售场景",
    riskScore: 84,
    riskLevel: "low",
    riskItems: [
      { text: "无近似驳回风险", ok: true },
      { text: "权属清晰无纠纷", ok: true },
      { text: "有效期充足", ok: true },
    ],
    items: [
      { name: "广告", group: "3501" },
      { name: "商业管理辅助", group: "3502" },
    ],
    applyDate: "2022-05-18",
    registerDate: "2023-02-14",
    expireDate: "2033-02-13",
    applicant: "广州某某商务咨询有限公司",
    similarGroups: "3501, 3502",
  },
  {
    id: "tm-8",
    name: "星盒季",
    initial: "星",
    registrationNo: "71234574",
    categoryCode: 43,
    categoryName: "餐饮",
    price: 6499,
    itemCount: 7,
    sameNameClasses: 2,
    gradient: "from-[#8B5CF6] to-[#EC4899]",
    status: "available",
    hot: true,
    scenes: ["food"],
    aiScore: 83,
    aiTags: ["年轻化", "餐饮友好"],
    aiReason: "名称时尚，适合餐饮连锁品牌",
    riskScore: 88,
    riskLevel: "low",
    riskItems: [
      { text: "无近似驳回风险", ok: true },
      { text: "权属清晰无纠纷", ok: true },
      { text: "有效期充足", ok: true },
    ],
    items: [
      { name: "餐厅", group: "4301" },
      { name: "快餐厅", group: "4301" },
    ],
    applyDate: "2023-04-01",
    registerDate: "2024-01-10",
    expireDate: "2034-01-09",
    applicant: "南京某某餐饮有限公司",
    similarGroups: "4301",
  },
  {
    id: "tm-9",
    name: "铭尚优品",
    initial: "铭",
    registrationNo: "71234575",
    categoryCode: 9,
    categoryName: "电子电器",
    price: 3999,
    originalPrice: 5800,
    itemCount: 8,
    sameNameClasses: 1,
    gradient: "from-[#2E6BFF] to-[#00C9A7]",
    status: "available",
    deal: true,
    dealTag: "天猫可用",
    scenes: ["ecommerce"],
    aiScore: 78,
    aiTags: ["性价比高", "电商友好"],
    aiReason: "特价商标，适合电商入驻",
    riskScore: 82,
    riskLevel: "low",
    riskItems: [
      { text: "无近似驳回风险", ok: true },
      { text: "权属清晰无纠纷", ok: true },
      { text: "有效期充足", ok: true },
    ],
    items: defaultItems.slice(0, 5),
    applyDate: "2019-07-20",
    registerDate: "2020-04-15",
    expireDate: "2030-04-14",
    applicant: "厦门某某电子有限公司",
    similarGroups: "0901",
  },
  {
    id: "tm-10",
    name: "优立达",
    initial: "优",
    registrationNo: "71234576",
    categoryCode: 35,
    categoryName: "广告销售",
    price: 2899,
    originalPrice: 4500,
    itemCount: 6,
    sameNameClasses: 1,
    gradient: "from-[#FF6B35] to-[#FEF3C7]",
    status: "available",
    deal: true,
    dealTag: "天猫可用",
    scenes: ["ecommerce"],
    aiScore: 76,
    aiTags: ["特价优选"],
    aiReason: "低价优质，适合初创电商",
    riskScore: 80,
    riskLevel: "low",
    riskItems: [
      { text: "无近似驳回风险", ok: true },
      { text: "权属清晰无纠纷", ok: true },
      { text: "有效期充足", ok: true },
    ],
    items: [{ name: "广告", group: "3501" }],
    applyDate: "2018-12-05",
    registerDate: "2019-09-20",
    expireDate: "2029-09-19",
    applicant: "福州某某传媒有限公司",
    similarGroups: "3501",
  },
  {
    id: "tm-11",
    name: "锐行天下",
    initial: "锐",
    registrationNo: "71234577",
    categoryCode: 9,
    categoryName: "电子电器",
    price: 4200,
    originalPrice: 6800,
    itemCount: 10,
    sameNameClasses: 2,
    gradient: "from-[#7C3AED] to-[#A78BFA]",
    status: "available",
    deal: true,
    dealTag: "京东可用",
    scenes: ["ecommerce", "tech"],
    aiScore: 79,
    aiTags: ["动感", "科技范"],
    aiReason: "名称有动感，适合运动科技产品",
    riskScore: 83,
    riskLevel: "low",
    riskItems: [
      { text: "无近似驳回风险", ok: true },
      { text: "权属清晰无纠纷", ok: true },
      { text: "有效期充足", ok: true },
    ],
    items: defaultItems.slice(0, 7),
    applyDate: "2020-02-28",
    registerDate: "2020-11-15",
    expireDate: "2030-11-14",
    applicant: "重庆某某科技有限公司",
    similarGroups: "0901, 0907",
  },
  {
    id: "tm-12",
    name: "源味小镇",
    initial: "源",
    registrationNo: "71234578",
    categoryCode: 30,
    categoryName: "食品",
    price: 3599,
    originalPrice: 5200,
    itemCount: 5,
    sameNameClasses: 1,
    gradient: "from-[#00C9A7] to-[#A4EAD4]",
    status: "available",
    deal: true,
    dealTag: "天猫可用",
    scenes: ["food"],
    aiScore: 77,
    aiTags: ["食品行业", "地域感"],
    aiReason: "适合食品、餐饮类品牌",
    riskScore: 81,
    riskLevel: "low",
    riskItems: [
      { text: "无近似驳回风险", ok: true },
      { text: "权属清晰无纠纷", ok: true },
      { text: "有效期充足", ok: true },
    ],
    items: [
      { name: "咖啡", group: "3001" },
      { name: "茶", group: "3002" },
    ],
    applyDate: "2019-04-10",
    registerDate: "2020-01-25",
    expireDate: "2030-01-24",
    applicant: "长沙某某食品有限公司",
    similarGroups: "3001, 3002",
  },
];
